name: 'CI'

on: [push]

jobs:
  build:
    name: 'Build site'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2

      - name: 'Set up Node'
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run code checks'
        run: |
          npm run format -- --check
          npm run lint
          npm run check

      - name: 'Build static assets'
        run: npm run build

      - if: startsWith(github.ref, 'refs/tags/v')
        name: 'Deploy site'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config user.name "${USER_NAME} via GitHub Actions"
          git config user.email "${USER_ID}+${USER_NAME}@users.noreply.github.com"
          npm run deploy
        env:
          USER_NAME: ${{ github.actor }}
          USER_ID: ${{ github.event.sender.id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
